name: 🐞 Reporte de Bug
description: Reporta un error en el proyecto
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar un bug. Por favor completa la siguiente información:
  - type: input
    id: entorno
    attributes:
      label: Entorno
      description: "Ej: Windows 10 / Ubuntu 22.04, Node 18.x, Chrome 139"
      placeholder: "Sistema operativo y versión"
    validations:
      required: true
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      description: "Descripción detallada para reproducir el bug"
      placeholder: "1. Ir a...\n2. Hacer click en...\n3. Ver el error"
    validations:
      required: true
  - type: textarea
    id: esperado
    attributes:
      label: Resultado esperado
      placeholder: "Explica qué debería pasar"
  - type: textarea
    id: capturas
    attributes:
      label: Evidencia
      description: "Adjunta logs o screenshots (opcional)"
